### ISSUE TITLE
Eject player at terminating station rather than Depot

### ISSUE THREAD

**Issue by cherbert** [jonafanho/Minecraft-Transit-Railway#207] opened 2021-11-08 11:39 UTC
**Is your feature request related to a problem? Please describe.**
Players are ejected from the train at sidings

**Describe the solution you'd like**
Eject the player at the final station on the route before the train leaves for the siding

**Additional Information**
Keep up the good work

**Comment by kettle-7** [comment] 2021-11-09 08:49
hmm maybe make it an option

annoying when you wanna make through trains

**Comment by jonafanho** [comment] 2022-04-22 19:00
Duplicate of #170

**Closed by jonafanho** 2022-04-22 19:00 UTC
Labels: enhancement
