### ISSUE TITLE
Display by empty space

### ISSUE THREAD

**Issue by AlexVin-Dev** [jonafanho/Minecraft-Transit-Railway#416] opened 2022-06-27 20:01 UTC
**Actual Behaviour**
It is displayed on an empty place when you are floating or high in the sky, then appears: entity.mtr.seat

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Add a mod for displaying blocks.
2. To swim, sometimes also appears high in the sky or an empty place.

**Screenshots**
![image](https://user-images.githubusercontent.com/15629077/176024549-8206b78e-2e07-4132-ace7-96ea6a3f1a6d.png)
**Environment**

- Minecraft Version: 1.18.2 Forge
- Installed Mods: 1.18.2 3.0.0

**Comment by jonafanho** [comment] 2022-06-28 06:54
Duplicate of #341

**Closed by jonafanho** 2022-06-28 06:54 UTC
Labels: duplicate, enhancement
