### ISSUE TITLE
Add buses to Minecraft Transit Railway PLEASE!

### ISSUE THREAD

**Issue by buscrazyfan995** [jonafanho/Minecraft-Transit-Railway#602] opened 2023-01-07 08:34 UTC
Hello, Can you please add buses to the mod? I want to create a bus system! Please!

Examples: https://youtu.be/4FS1lZgx7PM https://youtu.be/uDSTNc3fH68 https://youtu.be/pEhV2QsncWc 

WHERE WHERE WHERE WHERE WHERE WHERE WHERE WHERE WHERE WHERE **I WANT TO MAKE A BUS SYSTEM BUT BUSES ARENT RELEASED YET** WHERE WHERE WHERE WHERE WHERE WHERE WHERE WHERE WHERE WHERE

**Comment by XHG78999** [comment] 2023-01-07 08:41
Duplicated.
@pokOS has already mentioned it. The author has said that it will come soon(on discord).
There're already some bus packs, like Yutong U12 on discord and the Wuhan Bus 114E514 that made by me.

At present, you can built bus lines like default metro line and break rail nodes without flashing routes.

**Comment by buscrazyfan995** [comment] 2023-01-07 12:18
> Duplicated. @pokos has already mentioned it. The author has said that it will come soon(on discord). There're already some bus packs, like Yutong U12 on discord and the Wuhan Bus 114E514 that made by me.
> 
> At present, you can built bus lines like default metro line and break rail nodes without flashing routes.

What a pathetic statement from a normal player. This is called minimodding. It means you are acting like a mod when you are a normal person with NO PERKS. And where's your evidence of this being duplicated? Like you are defending the other people who want to create this little statement with no proof.

**Comment by XHG78999** [comment] 2023-01-07 13:02
> 

6
I think we shouldn't beat each other here. The author is not a machine. Before the officially supported solution comes out, the best way is to adopt an approximate solution that can last for a long time and has high robustness.
I don't know what you mean by "like mod", but this is a manifestation of community derivation.

**Comment by jonafanho** [comment] 2023-01-07 23:22
Duplicate of #522, also, @buscrazyfan995 please be respectful towards other members.

**Closed by jonafanho** 2023-01-07 23:22 UTC
Labels: duplicate, train-requests
