### ISSUE TITLE
Add faster rails to MTR Mod / Add "Super" rails to MTR mod

### ISSUE THREAD

**Issue by Neon4UltraPlays** [jonafanho/Minecraft-Transit-Railway#604] opened 2023-01-08 09:23 UTC
Hello MTR Mod, I want to suggest adding faster rails to MTR Mod.

I want to add 3 types of rails:

**Super Quartz Rail Connector (500 max speed)
Super Diamond Rail Connector (750 max speed)
Super Netherite Rail Connector (1250 max speed)**

I want to make a very long high-speed railway, a straight line that takes minutes to ride a train through 50,000 blocks. Super rail connectors require at least 1 block of netherite.

CRAFTING RECIPES:
Super Netherite Rail Connector
![super rail connector 3](https://user-images.githubusercontent.com/90380800/211189381-7f8b4964-f16c-40c3-b366-cc5ac41bf357.jpg)

Super Diamond Rail Connector
![super rail connector 2](https://user-images.githubusercontent.com/90380800/211189380-0743fad0-60ae-4d46-97cb-0fd88369dd78.jpg)

Super Quartz Rail Connector
![super rail connector 1](https://user-images.githubusercontent.com/90380800/211189382-6275522d-dc87-4f06-bea3-460865c6137c.jpg)

Please add this to Minecraft Transit Railway. Thank you!

**Comment by XHG78999** [comment] 2023-01-08 10:18
It will make some super highspeed lines like Maglev easier that now.

**Comment by Neon4UltraPlays** [comment] 2023-01-08 10:35
> It will make some super highspeed lines like Maglev easier that now.

Thank you!

FACT: I was originally going to suggest to add maglev rails with much higher speed and maglev rail nodes, with maglev depots and maglev stations, but I feel like that's too much.

**Comment by saleem0915** [comment] 2023-01-08 18:57
This would be a nice addition, but there have been instances where people were asking for faster rails, but they were declined for some sort of reason.

**Comment by chortle3** [comment] 2023-01-09 01:20
> There have been instances where people were asking for faster rails, but they were declined for some sort of reason.

Maybe because it's you @saleem0915! You try to deny/decline people's suggestions because they didn't have Patreon. If you dare tell that this guy do not have Patreon or something, this suggestion could be denied because he didn't subscribe to Patreon!

See, you told this guy that if he dosen't have patreon, the suggestion will be denied! Then he said no, POOF! This guy's suggestion is denied.
![Screenshot 2023-01-09 081851](https://user-images.githubusercontent.com/94771839/211228439-891b5ea3-db56-4c3d-a7fa-4f25928b21c6.png)

**Comment by XHG78999** [comment] 2023-01-09 02:56
Back to the content. The biggest question is that the chunk loader may not afford the speed. Because of the poop code of Bugjump(you know who i am say about), it may cause memory leak, and crash like windows memory security limition or watchdog errors.
Exactly, The highest speed of maglev speed is 590km/h(Japan Maglev Center Line), max test speed is 620km/h(CF600).  This digit of normal railway is 515km/h(TGV), max test speed is 605km/h(CRH380AM). So we think that we just need the rails about 600km/h.
So that, I'd like to change these speeds into 350, 400, 500, 600.

**Comment by XHG78999** [comment] 2023-01-09 02:57
Instead, there's a PR about custom speed rails. We can build the solution on this code.

**Comment by jonafanho** [comment] 2023-01-13 17:00
Duplicate of #373

**Closed by jonafanho** 2023-01-13 17:00 UTC
Labels: duplicate, enhancement
