### ISSUE TITLE
Texture lost in v3.0.1 1.18.1

### ISSUE THREAD

**Issue by Mi6A16** [jonafanho/Minecraft-Transit-Railway#422] opened 2022-07-03 13:08 UTC
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment] 2022-07-04 05:35
Duplicate of #414, not enough information

**Closed** 2022-07-04 05:35 UTC
Labels: duplicate, not enough information
