### ISSUE TITLE
Platform gates not opening

### ISSUE THREAD

**Issue by michelepestulnik** [jonafanho/Minecraft-Transit-Railway#503] opened 2022-09-17 15:16 UTC
**Expected Behaviour**
I place Automatic platform gates, and they are opening while the train doors are opening.

**Actual Behaviour**
Train arrives, train doors open, platform gates not.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Place them
2. Wait until train arrives
3. See the problem

**Crash Report**
(it didn't crash)

**Screenshots**
![image](https://user-images.githubusercontent.com/111139586/190863952-f69fc747-c550-4d35-9474-629e478c6f9d.png)
It is broken as you might see it.

**Environment**

- Minecraft Version: 1.19 Fabric
- Installed Mods: Joban Client, Mod Menu, London Underground, Minecraft Transit Railway, Fabric API

**Additional Information**
Nothing else.

**Comment by jonafanho** [comment] 2022-09-22 16:15
Duplicate of #365

**Closed by jonafanho** 2022-09-22 16:15 UTC
Labels: bug, duplicate

**Comment by saleem0915** [comment] 2022-11-14 16:15
It's just desync
