### ISSUE TITLE
1.19.2 issue with Jade mod

### ISSUE THREAD

**Issue by Zygus42** [jonafanho/Minecraft-Transit-Railway#504] opened 2022-09-22 13:34 UTC
**Expected Behaviour**
Nothing.

**Actual Behaviour**
When you look straight down, if you're too far away from a block for Jade to activate the info tab, the info tab opens anyway and has the mod name "Minecraft Transit Railway" in it.  See attached picture:
![2022-09-22_21 27 54](https://user-images.githubusercontent.com/20757445/191760431-a50b2042-351a-4e40-a821-5f3021b69c80.png)

**Reproduction Steps**
Steps to reproduce the behaviour:
1. start world, fly up, look down.

**Crash Report**
no crash.  Find logs attached:
[debug.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/9626248/debug.log)
[latest.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/9626249/latest.log)

**Screenshots**
see above.

**Environment**

- Minecraft Version:    forge-1.19.2-43.1.25-installer
- Installed Mods:
   MTR-forge-1.19.2-3.1.0
   architectury-6.2.46-forge
   MTR-LU-Addon-forge-1.19.2-3.1.0-1.2
   Jade-1.19.1-forge-8.2.2

**Additional Information**
Anything else you want to add?

**Comment by cherbert** [comment] 2022-09-22 14:14
This a Jade problem not an MTR mod problem.

**Comment by Kenny-Hui** [comment] 2022-09-22 14:33
Almost all tooltips mod suffers the same issue (Unless they allow the player to ignore an entity)

https://github.com/jonafanho/Minecraft-Transit-Railway/issues/400
Jade dev told us to hide the entity with their code, although it doesn't seems viable to bundle another dependency
(Esp due to the current setup we have to deal from 1.16.5 - 1.19, then there's also The One Probe, wthit and numerous other mods out there)

Long term would be to move the entity a little bit away from the player (Maybe make it stay right behind of the players)
Seems to be already on the [To-Do](https://github.com/jonafanho/Minecraft-Transit-Railway/projects/2) list

[WTHIT allows you to "blacklist" a tooltips](https://docs.bai.lol/wthit/config/blacklisting) with only a json file, I have not tried it though

**Comment by jonafanho** [comment] 2022-09-22 16:08
Duplicate of #400

**Closed by jonafanho** 2022-09-22 16:08 UTC
Labels: duplicate, mod compatibility
