### ISSUE TITLE
Broken texture report 

### ISSUE THREAD

**Issue by Mi6A16** [jonafanho/Minecraft-Transit-Railway#414] opened 2022-06-26 01:35 UTC
In v3.0.1 (1.18.1) Most textures  lost and changed to black and purple broken textures

**Comment by jonafanho** [comment] 2022-06-26 06:17
Duplicate of #413, not enough information

**Closed by jonafanho** 2022-06-26 06:17 UTC
Labels: duplicate, not enough information

**Comment by kettle-7** [comment] 2022-06-28 06:53
Is this the server only jar?
