### ISSUE TITLE
奇怪的“站站”、“Station Station”

### ISSUE THREAD

**Issue by BadHunyun** [jonafanho/Minecraft-Transit-Railway#172] opened 2021-10-04 12:01 UTC
**起因**
我当时在某个服务器玩，到某一个站的时候看见了个及其奇怪的东西：
![image](https://user-images.githubusercontent.com/83549585/135847723-579fcfcf-877c-4241-970e-9bdd98b3f487.png)

上面写着▮▮▮▮站站
              ▮▮▮▮Station Station

比较奇怪

**Comment by kettle-7** [comment] 2021-10-04 20:13
Heh yeah that's been needing to be fixed for a while ;~)

@jonafanho Maybe the brush could change whether or not it uses Station afterwards?

**Comment by zqtang10** [comment] 2022-01-07 13:59
可能是类似“xx火车站”这样的站名吧

**Comment by code2828** [comment] 2022-01-25 09:40
这是完全正常、无bug的行为
从打码前的内容可以看出，该站是一个“火车站”。辽宁沈阳市便有“沈阳站站”之类的地铁站名；
所以请不要因此而发issue。如果觉得实在很别扭，问问腐竹为啥要这么写。
建议关闭该issue。

en: This is an absolutely normal and bug-less behavior.
From the picture you give we can see that this metro station is a "railway station". Shenyang, Liaoning Province have metro stations named "Shenyang Railway Station Station"; so please don't open an issue. Instead, ask the server administrator is you do see this as an improper way to express.
Closing of this issue is suggested, or at least remove the "bug" label. (_sorry if I sound a little impolite or make grammar mistakes_)

**Comment by DreamUniverse843** [comment] 2022-02-02 11:32
这两天我也遇到了这个问题，不过我认为，站名是否自动补全的配置选项应当交给用户。
按照当前模组的自动补全，当存在火车站站名（例如“梦之城火车站”）我为了保证站名显示正常只能设置为“梦之城火车”，报站时既不通顺也不合理（下一站：梦之城火车？？）。虽然有诸如上楼所言“沈阳站站”的站名，但是对于不需要的用户确实是一个赘余。
另外把这个选择权交给用户可以保证有“站站”和“站”的需求用户都能兼顾到。
I've met this question as well,however,I suggest it should add an option to make the user decide if the station name will fill the "station" automatically.
For example,I have a station called "DreamCity Railway Station",if i follow the current status,the next-stop announces "The next stop is DreamCity Railway",obviously it's a little haunt to understand.Despite "Shenyangzhan Station" truly exists,it's a useless word for those who needn't "station".
What's more,it's reasonable to give the right to users so that it could be compatible with the users who prefer "station station" or just a single "station".

**Comment by ZiYueCommentary** [comment] 2022-02-04 12:38
> 这两天我也遇到了这个问题，不过我认为，站名是否自动补全的配置选项应当交给用户。 按照当前模组的自动补全，当存在火车站站名（例如“梦之城火车站”）我为了保证站名显示正常只能设置为“梦之城火车”，报站时既不容易理解也不合理（下一站：梦之城火车？？）。虽然有诸如上楼所言“沈阳站站”的站名，但是对于不需要的用户确实是一个赘余。 另外把这个选择权交给用户可以保证有“站站”和“站”的需求用户都能兼顾到。 I've met this question as well,however,I suggest it should add an option to make the user decide if the station name will fill the "station" automatically. For example,I have a station called "DreamCity Railway Station",if i follow the current status,the next-stop announces "The next stop is DreamCity Railway",obviously it's a little haunt to understand.Despite "Shenyangzhan Station" truly exists,it's a useless word for those who needn't "station". What's more,it's reasonable to give the right to users so that it could be compatible with the users who prefer "station station" or just a single "station".

我对这个方块做了一些优化，让玩家能够用木棍选择是否显示自动添加的“站Station”
等待pull request通过

**Comment by jonafanho** [comment] 2022-06-14 19:02
Duplicate of #146

**Closed by jonafanho** 2022-06-14 19:02 UTC
Labels: bug, duplicate
