### ISSUE TITLE
Add train's max speed limit and custom rail speed.

### ISSUE THREAD

**Issue by CokeStudios** [jonafanho/Minecraft-Transit-Railway#411] opened 2022-06-24 15:39 UTC
The train's speed limit could only be 20, 40, 60, 80, 120, 160, 200, 300.

Please add rails in custom speed limits.
Or add an input box under the train's acceleration setting to modify the train's max speed. (We can only input integers in the input box)

**Comment by jonafanho** [comment] 2022-06-24 15:42
Duplicate of #373

**Closed by jonafanho** 2022-06-24 15:42 UTC
Labels: duplicate, enhancement
