### ISSUE TITLE
Pathfinder refuses to work for some routes.

### ISSUE THREAD

**Issue by SachaStickman** [jonafanho/Minecraft-Transit-Railway#685] opened 2023-05-24 01:56 UTC
**Expected Behaviour**
I type in the train routes, click refresh path, pathfinder creates the route, train starts driving.

**Actual Behaviour**
I type in the train route, click refresh path, then nothing happens. The button for "refresh path" gets stuck in its clicked form and the route is never created no matter how long you wait. This has happened to 6 total routes so far. That's over a quarter of all of my routes and almost half of my tram routes. And this number seems to only increase every time I implement a new one. See the picture for those 6 route visualized on the map. This problem has only been encountered by tram routes so far.

Initially I thought it might be because those routes are too long for the pathfinder to handle but I clearly have longer tram routes that work just fine. It's also worth noting that these issues seem to appear more often in the newer routes. Maybe the growing tram network is becoming too large for the A.I. to handle?

What's also bugging me is that even though the pathfinding A.I. may take very long to generate longer routes, the A.I still has to finish the process at the end of the day or display an error message, right? But the problem is, that never happens no matter how much time passes which makes me really wonder what the heck the A.I. is doing when this happens. No matter what the problem is, there's definitely something wrong the Pathfinder.

**Reproduction Steps**
Steps to reproduce the behaviour:
I can try sending the world save if really needed.

**Crash Report**

**Screenshots**
The 6 routes in question. The green one seems to be the biggest problem as of now. Not even the segment inside the square worked.
![Bildschirmfoto 2023-05-24 um 03 28 37](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/130763596/022a60b7-759f-483e-8edc-27def165d103)

**Environment**

- Minecraft Version: 1.17.1
- Installed Mods: MTR, API, Time and Wind (All the most recent versions as of 24th May)

**Additional Information**
This is the second time I'm having problems with the pathfinding A.I.

**Comment by jonafanho** [comment] 2023-06-27 16:50
Duplicate of #352

**Closed by jonafanho** 2023-06-27 16:50 UTC
Labels: bug
