### ISSUE TITLE
Waterloggable Railway Nodes

### ISSUE THREAD

**Issue by sleepysapph** [jonafanho/Minecraft-Transit-Railway#484] opened 2022-08-31 06:30 UTC
**Is your feature request related to a problem? Please describe.**
It's very niche lol but i've got a friend who wants to build a completely underwater railway and the air block surrounding nodes is annoying them. very stupid request i know

**Describe the solution you'd like**
be able to right click with a water bucket to waterlog the node :) very simple heh

**Comment by jonafanho** [comment] 2022-09-02 17:44
Duplicate of #168

**Closed by jonafanho** 2022-09-02 17:44 UTC
Labels: enhancement
