### ISSUE TITLE
Train needs pantograph

### ISSUE THREAD

**Issue by AIDA64S** [jonafanho/Minecraft-Transit-Railway#165] opened 2021-09-24 18:01 UTC
Train needs pantograph

**Comment by cherbert** [comment] 2021-09-24 20:23
No they don't. There are far higher priorities.

**Comment by kettle-7** [comment] 2021-09-25 08:45
> Train needs pantograph

See the discord, somebody started to make but then we're tossing up over adding it because of lag. LaunchX added catenaires too, and him (and cherbert?) are making these addon packs for tfl stuff.

**Comment by AIDA64S** [comment] 2021-09-27 07:42
> > 火车需要裤子
> 
> 看到不和谐， 有人开始制造， 但后来我们因为滞后而放弃添加它。启动克斯也添加了猫科动物， 他 （和切尔伯特？



> 不， 他们没有。优先事项要高得多。我们连转向架都没有

hahaha,really

**Comment by AIDA64S** [comment] 2021-09-27 07:55
> > Train needs pantograph
> 
> See the discord, somebody started to make but then we're tossing up over adding it because of lag. LaunchX added catenaires too, and him (and cherbert?) are making these addon packs for tfl stuff.

I think catenaires can use rail's idea.They can use same formula so they are always parallel.
![image](https://user-images.githubusercontent.com/89268565/134867179-f9453055-c0f6-4817-8c4a-505deccfb2b8.png)

**Comment by kettle-7** [comment] 2021-09-27 08:14
LaunchX is making

**Comment by jonafanho** [comment] 2022-09-22 16:27
Duplicate of #56

**Closed by jonafanho** 2022-09-22 16:27 UTC
Labels: enhancement
