### ISSUE TITLE
Railway sign style selector

### ISSUE THREAD

**Issue by 52PD** [jonafanho/Minecraft-Transit-Railway#573] opened 2022-12-14 17:02 UTC
**Is your feature request related to a problem? Please describe.**
So I just noticed that currently there is one railway sign model style, which is based on the existing version first used in Tung Chung Line. However, I just found that there is also another two common railway sign version used in other MTR station:

One version is using in all pre-1990 stations (includes stations in Tsuen Wan Line, Kwun Tong Line (except 2002 and 2016 expansion stations) and Island Line (except 2015 expansion stations)
![Jordan_Station_2021_05_part1](https://user-images.githubusercontent.com/98044618/207658757-cd4e4af9-b84f-4106-b3f3-56d8fa6e9041.jpg)

Another version is using in all new stations since 2014
![HKU_Station_2018_06_part5](https://user-images.githubusercontent.com/98044618/207658862-f5530093-217d-4beb-8e52-278b1ffa91df.jpg)

**Describe the solution you'd like**
Based on this, I'm not sure if OK, in the future updates will we can a railway sign style selector in the page that we choose what icons shows on it?🤔

**Additional Information**
No, all information provided above.

**Comment by jonafanho** [comment] 2023-01-13 17:06
Duplicate of #563

**Closed by jonafanho** 2023-01-13 17:06 UTC
Labels: duplicate, enhancement

**Comment by Swiftiecott** [comment] 2025-09-10 20:41
> Duplicate of [#563](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues/563)

Sorry for long time responding.

I quickly checked what Issue #563 suggest, and I don't think the suggestion of Issue #563 and this are same thing.
Issue #563 is suggesting adding one-icon sign, while this one is suggesting different sign style.
