### ISSUE TITLE
Opening schedule from track on dedicated server freezes the game

### ISSUE THREAD

**Issue by Noaaan** [jonafanho/Minecraft-Transit-Railway#16] opened 2021-02-04 20:55 UTC
**Expected Behaviour**
Right clicking a track on a dedicated server should bring up the schedule. 

**Actual Behaviour**
When right clicking a track with an empty hand, the client freezes and a restart is forced.

**Reproduction Steps**
Right click a train track server side.

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods:
- [✔️] Adorn-1.13.0+1.16.5
  [✔️] adventurez-1.1.5
  [✔️] agape_space-0.0.6
  [✔️] antiqueatlas-5.4.4-fabric
  [✔️] anvil-crushing-recipes-1.0+MC1.16.2-1.16.5
  [✔️] AnvilFix-1.2.1-1.16
  [✔️] architectury-1.5.106-fabric
  [✔️] astromine-core-1.11.4+fabric-1.16.3
  [✔️] astromine-foundations-1.11.4+fabric-1.16.3
  [✔️] astromine-transportations-1.11.4+fabric-1.16.3
  [✔️] BetterCaves-fabric-1.16.2-1.0.3
  [✔️] BetterMineshafts-Fabric-1.16.4-1.0
  [✔️] bitsandchisels-2.0.0
  [✔️] blast-1.5
  [✔️] blockus-2.0.2+1.16.4
  [✔️] byg-1.1.3
  [✔️] CameraOverhaul-1.2.2-fabric-universal
  [✔️] campanion-1.3.3
  [✔️] canvas-mc116-1.0.1267
  [✔️] Cardinal-Components-API-2.7.10
  [✔️] ce_foodstuffs-1.1.2
  [✔️] cinderscapes-1.3.3
  [✔️] com.stann_co.drip-mod-1.0.0
  [✔️] comforts-fabric-0.0.1-1.16.4
  [✔️] Croptopia-1.16.4-5-FABRIC-1.2.0
  [✔️] curios-fabric-0.0.11-1.16.4
  [✔️] dawn-1.6.3
  [✔️] desolation-1.0.4.1
  [✔️] DungeonsMod-1.16.3-1.1.18
  [✔️] eldritch-mobs-1.6.8
  [✔️] enchantment-lore-1.1.1+MC1.16.1-1.16.5
  [✔️] extraorigins-1.16.5-1
  [✔️] fabric-api-0.30.0+1.16
  [✔️] fabric-language-kotlin-1.4.21+build.1
  [✔️] fermion-mc116-2.9.218
  [✔️] geckolib-fabric-1.16.5-3.0.18
  [✔️] glassential-fabric-1.16.4-1.1.5
  [✔️] guillotine-1.0.0
  [✔️] illuminations-1.4.4
  [✔️] indrev-1.7.15-BETA
  [✔️] kubejs-1605.3.6-build.162-fabric
  [✔️] lazydfu-0.1.1
  [✔️] lengthyladders-1.0.1
  [✔️] lessgreedypiglins-1.0.0
  [✔️] light-overlay-5.6.1
  [📁] literally_chunk_loader (folder)
  [✔️] literally-chunk-loader-1.16-2.0.1
  [✔️] lithium-fabric-mc1.16.4-0.6.0 (1)
  [✔️] make-every-biome-spawnable-lol-1.16.5-1.0.0
  [✔️] mcda-0.9.4
  [✔️] MCDoom-Mod-Fabric-1.16.5-3.9.3
  [✔️] Mesh-0.6.4-alpha.24+1.16.4
  [✔️] Modern-Industrialization-0.3.12
  [✔️] modmenu-1.16.5
  [✔️] MoEnchantments-1.13.8
  [✔️] Monster-of-the-ocean-depths-2.9-1.16.4
  [✔️] morerespawnanchors-1.0
  [✔️] mousewheelie-1.6.3+mc1.16.4
  [✔️] MTR-1.16-3.0.0-beta-3
  [✔️] mythicmetals-0.9.9
  [✔️] netherite-plus-mod-1.3.13-1.16.5-fabric
  [✔️] nookbuild-1.3.2
  [✔️] notchify-0.4.0-configmenu.1
  [✔️] notenoughcrashes-3.1.5-fabric
  [✔️] okzoomer-4.0.1+1.16.2
  [✔️] Origins-1.16.4-0.4.6
  [✔️] Origins-Classes-1.16.5-1.1.1
  [✔️] OverpoweredMending-Fabric-1.16.5-2.2.2
  [✔️] Patchouli-1.16.4-48-FABRIC
  [✔️] Pehkui-1.7.1+21w03a
  [✔️] phonos-0.1.1-beta
  [✔️] piglib-1.0.2+1.16
  [✔️] plantinajar-1.8.1
  [✔️] portaltags-2.1.0
  [✔️] RebornCore-1.16-4.6.4+build.117
  [✔️] repurposed_structures-1.16.4-1.7.4
  [✔️] respawnablepets-1.16.5-1
  [✔️] rhino-1.7.13-build.14
  [✔️] RoughlyEnoughItems-5.9.1
  [✔️] rpgstats-3.1.1+1.16.4
  [✔️] ruined-equipment-1.2.3
  [✔️] shulkerboxtooltip-2.3.4+1.16.4
  [✔️] SimpleBackpack_Fabric_1.16.5-1.0.38
  [✔️] SlimeSling-1.0.0
  [✔️] someforgepatchesported-1.0.0
  [✔️] spellbound-1.1.3
  [✔️] starlight-fabric-0.0.3
  [✔️] TechReborn-1.16-3.7.3+build.192
  [✔️] terrestria-2.1.7
  [✔️] the_bumblezone_fabric-1.16.5-2.2.17
  [✔️] traverse-3.3.1
  [✔️] vanguard-uninstaller
  [✔️] wild_explorer-1.3.1
  [✔️] wraith-alloy_forgery-1.0.4
  [✔️] wraith-enchant_giver-1.0.3
  [✔️] wraith-harvestscythes-1.0.9
  [✔️] wraith-smithee-0.2.3
  [✔️] x-hp-1.0.5
  [✔️] YungsApi-1.16.4-Fabric-1

**Additional Information**
I did not make the train schedule myself, though it happens to the other player as well.

**Comment by jonafanho** [comment] 2021-02-04 20:57
Hello, thank you for your bug report. Do you have a crash report? That would help a lot, thanks!

**Comment by Noaaan** [comment] 2021-02-05 09:28
If I had one I would provide this. Unfortunately this only indefinitely freezes the client, and does not crash the game. I do have the capabability of testing this on a dedicated server further though. Please let me know if I could help.

**Comment by jonafanho** [comment] 2021-02-05 16:50
Does it crash every time? Or only randomly? I've been having some issues with Fabric API 0.30.0+ recently, I had to downgrade to 0.29.3. I am not sure if that's the issue though.

**Comment by Noaaan** [comment] 2021-02-05 17:15
From the description of the player:
It does not **always** happen. It happens often though, but from the longer you play it seems like the freeze occurs more often.

**Comment by Noaaan** [comment] 2021-02-05 17:17
Also, I just experienced the "ConcurrentModificationException" that was mentioned from issue #13. Same modlist, excapt same stacktrace. Only lead there I have there is the [javadoc].(https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html)

**Comment by jonafanho** [comment] 2021-02-05 17:18
Is there a crash for the concurrent modification exception? Or just showing up in the console

**Comment by Noaaan** [comment] 2021-02-05 17:33
Just updated. Will notify you further if the issue persists.

**Comment by Noaaan** [comment] 2021-02-05 21:19
ConcurrentModificationException seems to not appear anymore, though the game will still freeze sometimes when opening the schedule. I tested it by holding right-click on the platform rail.
Note that the game does NOT crash, it freezes the client forcing the user to kill the process.

**Comment by jonafanho** [comment] 2021-02-05 21:21
Thanks for testing it! I am able to reproduce the freeze also, but I'm unsure of how to fix it since no crash report is generated. I will continue to investigate the issue.

**Comment by jonafanho** [comment] 2021-03-20 17:28
This should be fixed in beta-5. Please let me know if you encounter other issues, thanks!

**Closed by jonafanho** 2021-03-20 17:28 UTC
Labels: bug
